[phases.setup]
nixPkgs = ["...", "postgresql"]

[phases.install]
cmds = ["bundle install --deployment --without development test"]

[start]
cmd = "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
